
CHAR_SUCCESS = "✅"
CHAR_FAILED = "❌"
CHAR_SENT = "📨"


RM_RESPONSE_FAILED = "failed"
RM_RESPONSE_SUCCESS = "success"
RM_BLANK = ""
RM_PRESET_INVALIDPARAMS = "invalidparams"
RM_PRESET_BOTLACKSPERMS = "botlacksperms"
RM_PRESET_AUTHORLACKSPERMS = "authorlacksperms"

RM_MESSAGE_GENERAL_STARTING_SET = "Set *"
RM_MESSAGE_GENERAL_STARTING_REMOVE = "Removed *"
RM_MESSAGE_GENERAL_ENDING_IE = "*!"
RM_MESSAGE_GENERAL_INVALIDROLE = "Invalid Role!"
RM_MESSAGE_GENERAL_INVALIDPOINTSNUMBER = "Invalid Points Number!"
RM_MESSAGE_GENERAL_INVALIDDEMONS = "Invalid Demons!"
RM_MESSAGE_SETMODERATOR_SET = " set as MODERATOR role."
RM_MESSAGE_POINTSROLE_FAILEDEXISTS = "Points Role already exists for *"
RM_MESSAGE_POINTSROLE_FAILEDDOESNTEXIST = "Points Role doesn't exist for *"
RM_MESSAGE_DEMONSROLE_FAILEDEXISTS = "Demons Role already exists for *"
RM_MESSAGE_DEMONSROLE_FAILEDDOESNTEXIST = "Demons Role doesn't exist for *"
RM_MESSAGE_ADDPOINTSROLE_SET = "* to be a POINTS ROLE, points requirement: "
RM_MESSAGE_REMOVEPOINTSROLE_REMOVE = "* as a POINTS ROLE"
RM_MESSAGE_EDITPOINTSROLE_SET = "* POINTS ROLE number: "
RM_MESSAGE_ADDDEMONSROLE_SET = "* to be a DEMONS ROLE, demons requirement(s): "
RM_MESSAGE_REMOVEDEMONSROLE_REMOVE = "* as a DEMONS ROLE"

KEY_MODERATOR = "MODERATOR"

VALUE_REMOVED = "$REMOVED$"


FILE_PCMODS = "pcmods.txt"
FILE_PCPROLES = "pcproles.txt"
FILE_PCDROLES = "pcdroles.txt"


DS_METHOD_GET = "get"
DS_METHOD_ADD = "add"
DS_METHOD_REMOVE = "remove"
DS_METHOD_CHANGE = "change"

